version: '3.8'

services:
  lazada_db:
    image: postgres:16-alpine
    container_name: lazada_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: lazada
      POSTGRES_PASSWORD: lazada
      POSTGRES_DB: lazada
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - lazada_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lazada"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  lazada_db_data:
    driver: local
